#!/usr/bin/env bash

env FONT_RESULT_DIR="Cascadia-Code-Nerd-Font"                      ./patch-cascadia-code $@
env FONT_RESULT_DIR="Cascadia-Code-Nerd-Font-Adjusted-Line-Height" ./patch-cascadia-code -l $@
