#!/usr/bin/env bash

set -e

OUTPUT_DIR="out/Ligconsolata"
FONT_DIR=~/src/fonts/Inconsolata/otf
FONT_PATCHER_OPTIONS="--adjust-line-height --complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"

mkdir -p $OUTPUT_DIR

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/Ligconsolata-Regular.otf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/Ligconsolata-Bold.otf"
