#!/usr/bin/env bash

env FONT_NAME="Rec-Mono-SemiCasual-Nerd-Font"                      ./patch-recursive-semicasual $@
env FONT_NAME="Rec-Mono-SemiCasual-Nerd-Font-Adjusted-Line-Height" ./patch-recursive-semicasual -l $@
