#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-Etoile-Nerd-Font"                      ./patch-iosevka-etoile $@
env FONT_RESULT_DIR="Iosevka-Etoile-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-etoile -l $@
