#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-IBMPlexMono}"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-out}"
OUTPUT_DIR="${FONT_RESULT_DIR}/${FONT_NAME}"
FONT_DIR=~/src/fonts/IBMPlexMono/ttf
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: ${FONT_DIR}"

mkdir -p "$OUTPUT_DIR"

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-BoldItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Bold.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-ExtraLightItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-ExtraLight.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Italic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-LightItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Light.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-MediumItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Medium.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Regular.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-SemiBoldItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-SemiBold.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-TextItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Text.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-ThinItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/IBMPlexMono-Thin.ttf"
