#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-Sparkle-Nerd-Font"                      ./patch-iosevka-sparkle $@
env FONT_RESULT_DIR="Iosevka-Sparkle-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-sparkle -l $@
