#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-SS13-Nerd-Font"                      ./patch-iosevka-ss13 $@
env FONT_RESULT_DIR="Iosevka-SS13-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss13 -l $@
