#!/usr/bin/env bash

env FONT_RESULT_DIR="DaddyTimeMono-Nerd-Font"                      ./patch-daddy-time-mono $@
env FONT_RESULT_DIR="DaddyTimeMono-Nerd-Font-Adjusted-Line-Height" ./patch-daddy-time-mono -l $@
