#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-D2Coding}"
OUTPUT_DIR="out/${FONT_NAME}"
FONT_DIR=~/src/fonts/D2Coding/ttf
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: ${FONT_DIR}"

mkdir -p "$OUTPUT_DIR"

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/D2Coding.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/D2CodingBold.ttf"
