#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-Slab-Nerd-Font"                      ./patch-iosevka-slab $@
env FONT_RESULT_DIR="Iosevka-Slab-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-slab -l $@
