#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-fonts/font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-RecMonoCasual}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/RecMonoCasual
FONT_GLYPHS_OPTIONS="${FONT_GLYPHS_OPTIONS:---complete}"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "==> FONT_DIR: $FONT_DIR"
echo "--> ${FONT_SCRIPT} ${FONT_PATCHER_OPTIONS}"

mkdir -p $FONT_OUTPUT_DIR

"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-Light.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-LightItalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-Regular.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-Italic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-Medium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-MediumItalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-SemiBold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-SemiBoldItalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-Bold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMonoCasual-BoldItalic.ttf"
