#!/usr/bin/env bash

env FONT_RESULT_DIR="Rec-Mono-Duotone-Nerd-Font"                      ./patch-recursive-duotone $@
env FONT_RESULT_DIR="Rec-Mono-Duotone-Nerd-Font-Adjusted-Line-Height" ./patch-recursive-duotone -l $@
