#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-Daddy-Time-Mono}"
OUTPUT_DIR="out/${FONT_NAME}"
FONT_DIR=~/src/fonts/DaddyTimeMono/ttf
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: ${FONT_DIR}"

mkdir -p "$OUTPUT_DIR"

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/DaddyTimeMono.ttf"
UPDATE_FONT_SUB_FAMILY=yes ~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/DaddyTimeMono.ttf"
