#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-fonts/font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-Iosevka-SS07}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/Iosevka-SS07/ttf
FONT_GLYPHS_OPTIONS="--fontawesome --fontawesomeextension --fontlinux --octicons --powersymbols --pomicons --powerlineextra --material --weather"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ $FONT_CONFIG_OPTIONS --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "==> FONT_DIR: ${FONT_DIR}"
echo "--> ${FONT_SCRIPT} ${FONT_PATCHER_OPTIONS}"

mkdir -p "$FONT_OUTPUT_DIR"

# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-extralight.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-extralightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-extralightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-heavy.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-heavyitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-heavyoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-light.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-lightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-lightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-thin.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-thinitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-thinoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-bold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-bolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-boldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-extrabold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-extrabolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-extraboldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-italic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-medium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-mediumitalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-mediumoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-oblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-regular.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-semibold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-semibolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss07-semiboldoblique.ttf"
