#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-Recursive-Duotone}"
OUTPUT_DIR="out/${FONT_NAME}"
FONT_DIR=~/src/fonts/Recursive-Duotone
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"

mkdir -p $OUTPUT_DIR

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-Duotone-${RECURSIVE_VERSION}.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-DuotoneBold-${RECURSIVE_VERSION}.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-DuotoneBoldItalic-${RECURSIVE_VERSION}.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-DuotoneItalic-${RECURSIVE_VERSION}.ttf"
