#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-font-patcher/custom-font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-Inconsolata}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/Inconsolata/ttf
FONT_GLYPHS_OPTIONS="${FONT_GLYPHS_OPTIONS:---complete}"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"
echo "FONT_PATCHER_OPTIONS: ${FONT_PATCHER_OPTIONS}"

mkdir -p $FONT_OUTPUT_DIR

# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-Black.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-ExtraLight.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-Bold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-ExtraBold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-Light.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-Medium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-Regular.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiBold.ttf"
