#!/usr/bin/env bash

env FONT_RESULT_DIR="JetBrains-Mono-Nerd-Font"                      ./patch-jetbrains-mono $@
env FONT_RESULT_DIR="JetBrains-Mono-Nerd-Font-Adjusted-Line-Height" ./patch-jetbrains-mono -l $@

# env FONT_RESULT_DIR="JetBrains-Mono-Nerd-Font-Mono"                      ./patch-jetbrains-mono --mono $@
# env FONT_RESULT_DIR="JetBrains-Mono-Nerd-Font-Mono-Adjusted-Line-Height" ./patch-jetbrains-mono --mono -l $@
