#!/usr/bin/env bash

env FONT_RESULT_DIR="IBM-Plex-Mono-Nerd-Font"                      ./patch-ibm-plex-mono $@
env FONT_RESULT_DIR="IBM-Plex-Mono-Nerd-Font-Adjusted-Line-Height" ./patch-ibm-plex-mono -l $@
