#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-Recursive-Casual}"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-out}"
OUTPUT_DIR="${FONT_RESULT_DIR}/${FONT_NAME}"
FONT_DIR=~/src/fonts/Recursive-Casual
FONT_GLYPHS_OPTIONS="${FONT_GLYPHS_OPTIONS:---complete}"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"
echo "FONT_PATCHER_OPTIONS: ${FONT_PATCHER_OPTIONS}"

mkdir -p $OUTPUT_DIR

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-Casual.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-CasualBold.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-CasualBoldItalic.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-CasualItalic.ttf"
