#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-Term-Nerd-Font"                      ./patch-iosevka-term $@
env FONT_RESULT_DIR="Iosevka-Term-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-term -l $@
