#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-Recursive-Linear}"
OUTPUT_DIR="out/${FONT_NAME}"
FONT_DIR=~/src/fonts/Recursive-Linear
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"

mkdir -p $OUTPUT_DIR

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-Linear-${RECURSIVE_VERSION}.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-LinearBold-${RECURSIVE_VERSION}.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-LinearBoldItalic-${RECURSIVE_VERSION}.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/RecMono-LinearItalic-${RECURSIVE_VERSION}.ttf"
