#!/usr/bin/env bash

env FONT_NAME="Iosevka-SS10-Nerd-Font"                      ./patch-iosevka-ss10 $@
env FONT_NAME="Iosevka-SS10-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss10 -l $@

env FONT_NAME="Iosevka-SS12-Nerd-Font"                      ./patch-iosevka-ss12 $@
env FONT_NAME="Iosevka-SS12-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss12 -l $@

# env FONT_NAME="Iosevka-SS13-Nerd-Font"                      ./patch-iosevka-ss13 $@
# env FONT_NAME="Iosevka-SS13-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss13 -l $@

env FONT_NAME="Iosevka-SS14-Nerd-Font"                      ./patch-iosevka-ss14 $@
env FONT_NAME="Iosevka-SS14-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss14 -l $@
