#!/usr/bin/env bash

env UPDATE_FONT_SUB_FAMILY=yes FONT_NAME="MPlus-Nerd-Font"                      ./patch-mplus $@
env UPDATE_FONT_SUB_FAMILY=yes FONT_NAME="MPlus-Nerd-Font-Adjusted-Line-Height" ./patch-mplus -l $@
