#!/usr/bin/env bash

env FONT_RESULT_DIR="Inconsolata-Nerd-Font"                      ./patch-inconsolata $@
env FONT_RESULT_DIR="Inconsolata-Nerd-Font-Adjusted-Line-Height" ./patch-inconsolata -l $@
