#!/usr/bin/env bash

env FONT_RESULT_DIR="Inconsolata-Condensed-Nerd-Font"                      ./patch-inconsolata-condensed $@
env FONT_RESULT_DIR="Inconsolata-Condensed-Nerd-Font-Adjusted-Line-Height" ./patch-inconsolata-condensed -l $@
