#!/usr/bin/env bash

env FONT_RESULT_DIR="Victor-Mono-Nerd-Font"                      ./patch-victor-mono $@
env FONT_RESULT_DIR="Victor-Mono-Nerd-Font-Adjusted-Line-Height" ./patch-victor-mono -l $@
