#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-Comic-Shanns}"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-out}"
OUTPUT_DIR="${FONT_RESULT_DIR}/${FONT_NAME}"
FONT_DIR=~/src/fonts/ComicShanns/otf
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: ${FONT_DIR}"

mkdir -p "$OUTPUT_DIR"

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/comic-shanns.otf"
