#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-SS08-Nerd-Font"                      ./patch-iosevka-ss08 $@
env FONT_RESULT_DIR="Iosevka-SS08-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss08 -l $@
