#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-SS10-Nerd-Font"                      ./patch-iosevka-ss10 $@
env FONT_RESULT_DIR="Iosevka-SS10-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss10 -l $@
