#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-font-patcher/custom-font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-Inconsolata-Semi-Condensed}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/Inconsolata/ttf
FONT_GLYPHS_OPTIONS="${FONT_GLYPHS_OPTIONS:---complete}"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"
echo "FONT_PATCHER_OPTIONS: ${FONT_PATCHER_OPTIONS}"

mkdir -p $FONT_OUTPUT_DIR

# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedBlack.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedExtraLight.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensed.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedBold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedExtraBold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedLight.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedMedium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/Inconsolata-SemiCondensedSemiBold.ttf"
