#!/usr/bin/env bash

env FONT_NAME="Fantasque-Sans-Mono-NoLoopK-Nerd-Font"                      ./patch-fantasque-sans-mono-noloopk $@
env FONT_NAME="Fantasque-Sans-Mono-NoLoopK-Nerd-Font-Adjusted-Line-Height" ./patch-fantasque-sans-mono-noloopk -l $@
