#!/usr/bin/env bash

env FONT_RESULT_DIR="Rec-Mono-Casual-Nerd-Font"                      ./patch-rec-mono-casual $@
env FONT_RESULT_DIR="Rec-Mono-Casual-Nerd-Font-Adjusted-Line-Height" ./patch-rec-mono-casual -l $@
