#!/usr/bin/env bash

env FONT_NAME="Daddy-Time-Mono-Nerd-Font"                      ./patch-daddy-time-mono $@
env FONT_NAME="Daddy-Time-Mono-Nerd-Font-Adjusted-Line-Height" ./patch-daddy-time-mono -l $@
