#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-NanumGothicCoding}"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-out}"
OUTPUT_DIR="${FONT_RESULT_DIR}/${FONT_NAME}"
FONT_DIR=~/src/fonts/NanumGothicCoding/ttf
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: ${FONT_DIR}"

mkdir -p "$OUTPUT_DIR"

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/NanumGothicCoding.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/NanumGothicCoding-Bold.ttf"
