#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-fonts/font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-Iosevka-SS10}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/Iosevka-SS10
FONT_GLYPHS_OPTIONS="--fontawesome --fontawesomeextension --fontlinux --octicons --powersymbols --pomicons --powerlineextra --material --weather"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ $FONT_CONFIG_OPTIONS --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "==> FONT_DIR: ${FONT_DIR}"
echo "--> ${FONT_SCRIPT} ${FONT_PATCHER_OPTIONS}"

mkdir -p "$FONT_OUTPUT_DIR"

# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-extralight.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-extralightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-extralightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-heavy.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-heavyitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-heavyoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-light.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-lightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-lightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-thin.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-thinitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-thinoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-bold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-bolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-boldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-extrabold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-extrabolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-extraboldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-italic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-medium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-mediumitalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-mediumoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-oblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-regular.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-semibold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-semibolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-ss10-semiboldoblique.ttf"
