#!/usr/bin/env bash

./patch-all-iosevka --complete
./patch-all-iosevka-slab --complete
./patch-all-iosevka-ss07 --complete
./patch-all-iosevka-ss14 --complete
./patch-all-jetbrains-mono
./patch-all-victor-mono
./patch-all-fira-code
./patch-all-cascadia-code
./patch-all-inconsolata-semi-condensed
./patch-all-mplus
./patch-all-mplus-original
