#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-SS07-Nerd-Font"                      ./patch-iosevka-ss07 $@
env FONT_RESULT_DIR="Iosevka-SS07-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-ss07 -l $@
