#!/usr/bin/env bash

env FONT_RESULT_DIR="Iosevka-Aile-Nerd-Font"                      ./patch-iosevka-aile $@
env FONT_RESULT_DIR="Iosevka-Aile-Nerd-Font-Adjusted-Line-Height" ./patch-iosevka-aile -l $@
