#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-fonts/font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-Iosevka-Term}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/Iosevka-Term
FONT_GLYPHS_OPTIONS="--fontawesome --fontawesomeextension --fontlinux --octicons --powersymbols --pomicons --powerlineextra --material --weather"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ $FONT_CONFIG_OPTIONS --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "==> FONT_DIR: ${FONT_DIR}"
echo "--> ${FONT_SCRIPT} ${FONT_PATCHER_OPTIONS}"

mkdir -p "$FONT_OUTPUT_DIR"

# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-extralight.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-extralightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-extralightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-heavy.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-heavyitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-heavyoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-light.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-lightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-lightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-thin.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-thinitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-thinoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-bold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-bolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-boldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-extrabold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-extrabolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-extraboldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-italic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-medium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-mediumitalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-mediumoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-oblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-regular.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-semibold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-semibolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-term-semiboldoblique.ttf"
