#!/usr/bin/env bash

set -e

FONT_NAME="${FONT_NAME:-AnonymousPro}"
OUTPUT_DIR="out/${FONT_NAME}"
FONT_DIR=~/src/fonts/AnonymousPro/ttf
FONT_PATCHER_OPTIONS="--complete $@ --output $OUTPUT_DIR -q --no-progressbars"

echo "FONT_DIR: $FONT_DIR"

mkdir -p $OUTPUT_DIR

~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/Anonymous Pro B.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/Anonymous Pro BI.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/Anonymous Pro I.ttf"
~/src/nerd-fonts/font-patcher $FONT_PATCHER_OPTIONS "${FONT_DIR}/Anonymous Pro.ttf"
