#!/usr/bin/env bash

export FONT_RESULT_DIR="custom"
export USE_COMPLETE_NAME="true"

./patch-all-iosevka      --removeligatures --configfile iosevka.config.json
./patch-all-iosevka-slab --removeligatures --configfile iosevka.config.json
./patch-all-iosevka-ss07 --removeligatures --configfile iosevka.config.json
./patch-all-iosevka-ss14 --removeligatures --configfile iosevka.config.json
./patch-all-fira-code    --removeligatures --configfile fira_code.config.json
