#!/usr/bin/env bash

set -e

FONT_SCRIPT="$HOME/src/nerd-fonts/font-patcher"
FONT_RESULT_DIR="${FONT_RESULT_DIR:-Iosevka}"
OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-out}"
FONT_OUTPUT_DIR="${OUTPUT_ROOT_DIR}/${FONT_RESULT_DIR}"
FONT_DIR=~/src/fonts/Iosevka/ttf
FONT_GLYPHS_OPTIONS="--fontawesome --fontawesomeextension --fontlinux --octicons --powersymbols --pomicons --powerlineextra --material --weather"
FONT_PATCHER_OPTIONS="$FONT_GLYPHS_OPTIONS $@ $FONT_CONFIG_OPTIONS --output $FONT_OUTPUT_DIR -q --no-progressbars"

echo "==> FONT_DIR: ${FONT_DIR}"
echo "--> ${FONT_SCRIPT} ${FONT_PATCHER_OPTIONS}"

mkdir -p "$FONT_OUTPUT_DIR"

# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-extralight.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-extralightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-extralightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-heavy.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-heavyitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-heavyoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-light.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-lightitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-lightoblique.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-thin.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-thinitalic.ttf"
# "$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-thinoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-bold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-bolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-boldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-extrabold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-extrabolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-extraboldoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-italic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-medium.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-mediumitalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-mediumoblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-oblique.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-regular.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-semibold.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-semibolditalic.ttf"
"$FONT_SCRIPT" $FONT_PATCHER_OPTIONS "${FONT_DIR}/iosevka-semiboldoblique.ttf"
