#!/usr/bin/env bash

./patch-all-iosevka-ss02
./patch-all-iosevka-ss03
./patch-all-iosevka-ss05
./patch-all-iosevka-ss07
# ./patch-all-iosevka-ss08
./patch-all-iosevka-ss10
./patch-all-iosevka-ss12
# ./patch-all-iosevka-ss13
./patch-all-iosevka-ss14
