#!/usr/bin/env bash

env FONT_RESULT_DIR="Inconsolata-Semi-Condensed-Nerd-Font"                      ./patch-inconsolata-semi-condensed $@
env FONT_RESULT_DIR="Inconsolata-Semi-Condensed-Nerd-Font-Adjusted-Line-Height" ./patch-inconsolata-semi-condensed -l $@
