#!/usr/bin/env bash

set -e

FONT_DIR=$HOME/src/fonts

mkdir -p ${FONT_DIR}

function extract-xz() {
    local font="${FONT_DIR}/$1"
    local dir="${FONT_DIR}/$2"
    if [ -e "$font" ]; then
        mkdir -p "$dir"
        echo tar --keep-newer-files -xf $font -C "$dir"
        tar --keep-newer-files -xf $font -C "$dir" &>/dev/null
    fi
}

function extract-zip() {
    local font="${FONT_DIR}/$1"
    local dir="${FONT_DIR}/$2"
    if [ -e "$font" ]; then
        mkdir -p "$dir"
        echo unzip -q -o $font -d "$dir"
        unzip -q -o $font -d "$dir"
    fi
}

function fix-mplus-font() {
    local dir="${FONT_DIR}/MPlus-Original"
    if [ -d "$dir/063-OTF-NO_REMOVE_OVERLAP" ]; then
        ln -sfn "$dir/063-OTF-NO_REMOVE_OVERLAP" "$dir/otf"
    fi
    local dir="${FONT_DIR}/MPlus"
    if [ -d "$dir/063-OTF" ]; then
        ln -sfn "$dir/063-OTF" "$dir/otf"
    fi
}

function fix-inconsolata-font() {
    local dir="${FONT_DIR}/Inconsolata"
    if [ -d "$dir/fonts/ttf" ]; then
        ln -sfn "$dir/fonts/ttf" "$dir/ttf"
    fi
}

function fix-ibm-plex-mono-font() {
    local dir="${FONT_DIR}/IBM-Plex-Mono"
    if [ ! -d "$dir" ]; then
        mkdir "$dir"
    fi
    local src_dir="${FONT_DIR}/IBM-Plex/TrueType/IBM-Plex-Mono"
    if [ -d "$src_dir" ]; then
        ln -sfn "$src_dir" "$dir/ttf"
    fi
}

function fix-sudo-font() {
    local dir="${FONT_DIR}/Sudo"
    if [ -d "$dir/sudo" ]; then
        ln -sfn "$dir/sudo" "$dir/ttf"
    fi
}

extract-xz  "mplus-063-OTF-NO_REMOVE_OVERLAP.tar.xz" "MPlus-Original"
extract-xz  "mplus-063-OTF.tar.xz"                   "MPlus"
extract-zip "CascadiaCode-2009.14.zip"               "CascadiaCode"
extract-zip "Fira_Code_v5.2.zip"                     "FiraCode"
extract-zip "IBM-Plex-v5.1.3.zip"                    "IBM-Plex"
extract-zip "Inconsolata-v3.000.zip"                 "Inconsolata"
extract-zip "JetBrainsMono-2.002.zip"                "JetBrainsMono"
extract-zip "JuliaMono.zip"                          "JuliaMono/ttf"
extract-zip "VictorMonoAll.zip"                      "VictorMono"
extract-zip "sudo-v0.52.zip"                         "Sudo"
extract-zip "ttf-iosevka-3.6.3.zip"                  "Iosevka"
extract-zip "ttf-iosevka-slab-3.6.3.zip"             "Iosevka-Slab"
extract-zip "ttf-iosevka-ss07-3.6.3.zip"             "Iosevka-SS07"
extract-zip "ttf-iosevka-ss14-3.6.3.zip"             "Iosevka-SS14"

fix-ibm-plex-mono-font
fix-inconsolata-font
fix-mplus-font
fix-sudo-font
