#!/usr/bin/env ruby

CMD = '7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on %s %s'
DIR = File.expand_path(File.join('.', ARGV[0] || 'out'))

def zip_fonts
  puts "*** DIR = #{DIR}"
  Dir.glob(File.join(DIR, '*')).select { |f| File.directory?(f) }.sort.each do |font_dir|
    puts "==> Font Dir: #{font_dir}"
    dirname = File.dirname(font_dir)
    basename = File.basename(font_dir)
    zip_file_name = "#{basename}.7z"
    zip_file = File.join(dirname, zip_file_name)
    next if File.exist?(zip_file)
    cmd = format(CMD, zip_file.inspect, font_dir.inspect)
    puts "--> Running: #{cmd}"
    `#{cmd}`
  end
end

zip_fonts
